import pandas as pd
pd.set_option('display.max_columns', 8)
general = pd.read_csv('../files/test/general.csv')
parental = pd.read_csv('../files/test/prenatal.csv')
sports = pd.read_csv('../files/test/sports.csv')
parental.rename(columns={'HOSPITAL': 'hospital', 'Sex': 'gender'}, inplace=True)
sports.rename(columns={'Hospital': 'hospital', 'Male/female': 'gender'}, inplace=True)
merged = pd.concat([general, parental, sports], ignore_index=True).drop(columns=['Unnamed: 0'])
merged.dropna(how="all", inplace=True)
# print(merged.query("gender == 'female' | gender == 'woman'"))
merged.replace(to_replace={'gender': {'female': 'f', 'woman': 'f', 'male': 'm', 'man': 'm'}}, inplace=True)
# print(merged.query("blood_test.isnull()"))
merged.fillna(value={'gender': 'f', 'bmi': 0, 'diagnosis': 0, 'blood_test': 0, 'ecg': 0, 'ultrasound': 0, 'mri': 0, 'xray': 0, 'children': 0, 'months': 0}, inplace=True)
print("Data shape:", merged.shape)
# print(merged.query("blood_test == 0"))
print(merged.sample(n=20, random_state=30))