import pandas as pd
pd.set_option('display.max_columns', 8)
general = pd.read_csv('../files/test/general.csv')
parental = pd.read_csv('../files/test/prenatal.csv')
sports = pd.read_csv('../files/test/sports.csv')
parental.rename(columns={'HOSPITAL': 'hospital', 'Sex': 'gender'}, inplace=True)
sports.rename(columns={'Hospital': 'hospital', 'Male/female': 'gender'}, inplace=True)
merged = pd.concat([general, parental, sports], ignore_index=True).drop(columns=['Unnamed: 0'])
merged.dropna(how="all", inplace=True)
merged.replace(to_replace={'gender': {'female': 'f', 'woman': 'f', 'male': 'm', 'man': 'm'}}, inplace=True)
merged.fillna(value={'gender': 'f', 'bmi': 0, 'diagnosis': 0, 'blood_test': 0, 'ecg': 0, 'ultrasound': 0, 'mri': 0, 'xray': 0, 'children': 0, 'months': 0}, inplace=True)
print('The answer to the 1st question is', end=' ')
print(*merged['hospital'].value_counts().reset_index().query("count == count.max()").hospital)
print('The answer to the 2nd question is', end=' ')
print(round(merged.query("hospital == 'general' & diagnosis == 'stomach'").shape[0] / merged.query("hospital == 'general'").shape[0], 3))
print('The answer to the 3rd question is', end=' ')
print(round(merged.query("hospital == 'sports' & diagnosis == 'dislocation'").shape[0] / merged.query("hospital == 'sports'").shape[0], 3))
print('The answer to the 4th question is', end=' ')
print(abs(merged.query("hospital == 'general'").age.median() - merged.query("hospital == 'sports'").age.median()))
max_blood_test = merged.pivot_table(index='hospital', columns='blood_test', values='months', aggfunc='count').reset_index().query("t == t.max()")
print('The answer to the 5th question is', *max_blood_test.hospital, ',', *max_blood_test.t, 'blood tests')